/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatMsg {
        "UserName": string;
        "avatar": string;
        "isRemote": boolean;
        "msg": string;
        "timestamp": string;
    }
    interface ChatWindow {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLChatMsgElement extends Components.ChatMsg, HTMLStencilElement {
    }
    var HTMLChatMsgElement: {
        prototype: HTMLChatMsgElement;
        new (): HTMLChatMsgElement;
    };
    interface HTMLChatWindowElement extends Components.ChatWindow, HTMLStencilElement {
    }
    var HTMLChatWindowElement: {
        prototype: HTMLChatWindowElement;
        new (): HTMLChatWindowElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "chat-msg": HTMLChatMsgElement;
        "chat-window": HTMLChatWindowElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChatMsg {
        "UserName"?: string;
        "avatar"?: string;
        "isRemote"?: boolean;
        "msg"?: string;
        "timestamp"?: string;
    }
    interface ChatWindow {
        "onNewMsgSubmitted"?: (event: CustomEvent<String>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "chat-msg": ChatMsg;
        "chat-window": ChatWindow;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-msg": LocalJSX.ChatMsg & JSXBase.HTMLAttributes<HTMLChatMsgElement>;
            "chat-window": LocalJSX.ChatWindow & JSXBase.HTMLAttributes<HTMLChatWindowElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
